import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

import css from './TermsOfService.css';

const TermsOfService = props => {
  const { rootClassName, className } = props;
  const classes = classNames(rootClassName || css.root, className);

  // prettier-ignore
  return (
    <div className={classes}>
      <p className={css.lastUpdated}>Last updated: June 3, 2019</p>

<p>Intro<br />Motomo Pty Ltd, referred to as (&ldquo;Motomo&rdquo;, &ldquo;we&rdquo; or &ldquo;us&rdquo;) provides an online car booking service that connects existing vehicle rental businesses with customers seeking to book those vehicles. Motomo is accessible online through motomo.io and as an application for mobile devices. Motomo&rsquo;s website, blog, mobile applications and associated services are collectively referred to as &ldquo;the Services&rdquo;. &nbsp;By accessing or using the services, including by communicating with us or other Motomo users, you agree to comply with, and be legally bound by, the provisions of these Terms of Service (&ldquo;Terms&rdquo;), whether or not you become a registered user of the Services. These terms govern your access to and use of the Services and constitute a legally agreements between you and Motomo.</p>
<p>These terms, together with Motomo&rsquo;s privacy policy, constitute the &ldquo;Agreement&rdquo; between you and Motomo ( each a &ldquo;Party&rdquo; and together &ldquo;the Parties&rdquo;).</p>
<p>Modification</p>
<p>Motomo reserves the right, at our sole discretion, to modify our Services or to modify these Terms at any time. If we modify these Terms, we will post the modification on our Services. We will also update the &ldquo;Last Revised&rdquo; date at the top of these Terms. By continuing to access or use our Services after we have posted a modification or have provided you with notice of modification, you are indicating that you agree to be bound by the modified Terms. If the modified terms are not If the modified Terms are not acceptable to you, your sole recourse is to stop using and accessing the Services and close your Motomo Account within 30 days, in which case the previous effective version of these Terms will apply to you, unless you have used the Services during the intervening 30 day period, in which case the new version of these Terms will apply to you.</p>
<p><br />If you have any questions for us concerning the Agreement, or Motomo generally, please contact us at support@motomo.io.</p>
<p>Terms of service</p>
<p>Eligibility. Our Services are intended solely for persons who are 25 or older. Any use of the Services by anyone under 25 is expressly prohibited.</p>
<p>Registration. To access certain features of the Services, you must sign up for an account with us (a &ldquo;Motomo Account&rdquo;) by providing us your email address and creating a password.</p>
<p>Verification. When you list or book a vehicle, you provide us with certain information about yourself to enable us to verify your identity in order to become a &ldquo;Driver&rdquo;. You promise to provide complete and accurate information to Motomo about yourself and your vehicle(s), if applicable. Where permitted, Motomo has the right, but not the obligation, to undertake screenings, checks, and processes designed to help verify or check the identities and/or backgrounds of users and vehicles, including driving history and driver&rsquo;s license validity. Motomo does not endorse any vehicle, user, or a user&rsquo;s background, or commit to undertake any specific screening process. Motomo may in its sole discretion use third party services to verify the information you provide to us and to obtain additional related information and corrections where applicable, and you hereby authorize Motomo to request, receive, use, and store such information. Motomo may accept or reject your application to become a Driver in its sole and absolute discretion. Motomo may, but does not commit to, undertake efforts to ensure the safety of vehicles shared through the Services. We do not make any representations about, confirm, or endorse the safety or roadworthiness of any vehicles beyond our policies that require vehicle owners to ensure their vehicles are in safe and operable condition, legally registered to be driven on public roads, not be in a salvaged/branded/written state, not subject to any applicable safety recalls, and otherwise satisfy our eligibility requirements.</p>
<p>&nbsp;</p>
<p>Ongoing Information Updates. You promise to update the information you have provided to Motomo in the event of any changes to your contact information, or background. Specifically with respect to your contact information, Motomo may deliver notices to you at the most recent email, telephone, or address provided by you, and those notices will be considered valid even if you no longer maintain the email account, telephone number, or receive mail at that address unless you provide updated contact information to us. Also, you are, and will be solely responsible for, all of the activity that occurs through your Motomo Account, so please keep your password and Motomo Account information secure. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your Motomo Account, whether or not you have authorized such activities or actions. You will immediately notify Motomo of any actual or suspected unauthorized use of your Motomo Account. We are not responsible for your failure to comply with this clause, or for any delay in shutting down or protecting your Motomo Account after you have reported unauthorized access to us.</p>
<p><br />Your Commitments. You agree that you will always use your Motomo Account and the Services in compliance with these Terms, applicable law, and any other policies and standards provided to you by Motomo. As a rental vehicle company (&ldquo;host&rdquo;), you commit that you will provide a safe and legally registered and insured vehicle, in none of the following conditions, non-salvage/written off, in good mechanical condition, on time to the traveler or driver who is a Driver ( &ldquo;driver&rdquo;). As a driver, you commit that you&rsquo;ll be a legally licensed driver and provide proof to the host of a current, valid driver&rsquo;s license, who will treat the vehicle and any applicable Extras well and will take all reasonable measures to return the vehicle and any applicable Extras on time and in essentially the same condition as received. In connection with your use of or access to the Services you may not, and you agree that you will not, nor advocate, encourage, request, or assist any third party to:</p>
<p>Violate any law, including:</p>
<p>breach, violate, and/or circumvent any local, state, provincial/territorial, regional, or national law or other law or regulation, or any order of a court, including, without limitation, airport regulations and tax regulations, licensing or registration requirements, or third party rights;</p>
<p>post false, inaccurate, misleading, defamatory, or libelous content;</p>
<p>infringe, reproduce, perform, display, distribute, reverse engineer, or prepare derivative works from content that belongs to or is licensed to Motomo, or that comes from the Services and belongs to another Motomo user or to a third party, including works covered by any copyrights, trademark, patent, or other intellectual property, privacy, publicity, moral, or contractual rights, except with prior express written permission of Motomo;</p>
<p>Dilute, tarnish, or otherwise harm the Motomo brand in any way, including:</p>
<p>through unauthorized use of Motomo and/or user content;</p>
<p>registering and/or using Motomo or derivative terms in domain names, trade names, trademarks, or otherwise;</p>
<p>registering and/or using domain names, trade names, trademarks, social media account names, or other means of identification that closely imitate or are confusingly similar to Motomo domains, trademarks, taglines, promotional campaigns, or Motomo and/or user content.</p>
<p>Provide or submit any false information, including:</p>
<p>false name, date of birth, driver&rsquo;s license, payment method, credit card, insurance, or other personal information;</p>
<p>a claim, or respond to a claim (for example about damage to a vehicle), with false or misleading information;</p>
<p>offer, as a host, any vehicle or optional Extra that you do not yourself own or have authority to share;</p>
<p>offer, as a host, any vehicle that may not be shared for compensation pursuant to the terms and conditions of an agreement with a third party, including, but not limited to, a lease or financing agreement;</p>
<p>offer, as a host, any vehicle that has a salvaged, branded, written off, washed or that is not safe, legally registered, or not insured to be driven on public roads;</p>
<p>offer, as a host, any Extra that is not safe, clean, and acceptable for the use it is intended;</p>
<p>book or drive any vehicle without a valid driver&rsquo;s license;</p>
<p>any listing with false or misleading information, or any listing with a price that you do not intend to honor;</p>
<p>register for a Motomo Account on behalf of an individual other than yourself;</p>
<p>impersonate any person or entity, or falsify or otherwise misrepresent yourself or your affiliation with any person or entity;</p>
<p>Fail to honor your commitments, including:</p>
<p>fail to pay fees, penalties, or other amounts owed to Motomo &nbsp;or another user;</p>
<p>fail, as either a driver or host, to timely deliver, make available, or return any vehicle and optional Extras, unless you have a valid reason as set out in our Policies;</p>
<p>use the Services to find a host or driver, and then complete a transaction partially or wholly independent of the Services, in order to circumvent the obligation to pay any fees related to Motomo&rsquo;s provision of the Services or for any other reasons (aka, gray market transactions);</p>
<p>transfer your Motomo Account and/or user ID to another party without our consent;</p>
<p>allow anyone other than a driver with whom you are traveling to drive the vehicle you have booked;</p>
<p>list or provide to a driver a vehicle that is subject to a safety recall without first properly addressing the matter subject to the recall;</p>
<p>leave a vehicle unlocked or running or unattended with the keys inside, except where instructed to do so directly by Motomo in certain limited circumstances.</p>
<p>Harm or threaten to harm users of our community, including:</p>
<p>&ldquo;stalk&rdquo; or harass any other Motomo user or collect or store any personally identifiable information about any other user other than for purposes of transacting as a Motomo owner or driver in accordance with these Motomo;</p>
<p>engage in physically or verbally abusive or threatening conduct;</p>
<p>use our Services to transmit, distribute, post, or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information, or credit, debit, calling card, or account numbers;</p>
<p>treat anyone differently based on the way they look, who they love, what they believe, how they self-identify, where they&rsquo;re from, or when they were born. Discrimination of any kind is not tolerated in the Motomo community;</p>
<p>Use the Services for your own unrelated purposes, including to:</p>
<p>contact a host for any purpose other than in relation to a booking or said host&rsquo;s vehicle(s) or listing(s);</p>
<p>contact a driver for any purpose other than in relation to a booking or such driver&rsquo;s use of the Services;</p>
<p>commercialize any content found on Motomo or software associated with our Services, including reviews;</p>
<p>harvest or otherwise collect information about users without their and our consent;</p>
<p>recruit or otherwise solicit any user to join third party services or websites that are competitive to Motomo, without Motomo&rsquo;s prior written approval;</p>
<p>Interfere with the operation of the Services, including by:</p>
<p>interfering with any other user&rsquo;s listings;</p>
<p>entering into a Motomo transaction with a member of your family, household, friend, colleague, or acquaintance;</p>
<p>distributing or posting spam, unsolicited or bulk electronic communications, chain letters, or pyramid schemes;</p>
<p>distributing viruses or any other technologies such as cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, backdoors, packet or IP spoofing, forged routing or e-mail address information, or similar methods or technology that may disrupt or interfere with the operation or provision of our Services, or harm Motom or the interests or property of others;</p>
<p>bypassing robot exclusion headers, interfering with the working of the Services, or imposing an unreasonable or disproportionately large load on our infrastructure;</p>
<p>systematically retrieving data or other content from our Services to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory, or the like, whether by manual methods, or through the use of bots, crawlers, spiders, or otherwise;</p>
<p>using display mirroring or framing the Services or any individual element within the Services, Motomo&rsquo;s name, any Motomo trademark, logo, or other proprietary information, or the layout and design of any page or form contained on a page in the Services, without Motomo&rsquo;s express written consent;</p>
<p>accessing, tampering with, or using non-public areas of the Services, Motomo&rsquo;s computer systems, or the technical delivery systems of Motomo&rsquo;s providers;</p>
<p>attempting to probe, scan, or test the vulnerability of any of Motomo&rsquo;s system or network or breach any security or authentication measures;</p>
<p>avoiding, bypassing, removing, deactivating, impairing, descrambling, or otherwise circumventing any technological measure implemented by Motomo or any of Motomo&rsquo;s providers or any other third party (including another user) to protect the Services;</p>
<p>forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services to send altered, deceptive, or false source-identifying information;</p>
<p>attempting to decipher, decompile, disassemble, or reverse engineer any of the software used to provide the Services; or</p>
<p>endeavoring to circumvent a suspension, termination, or closure of your Motomo Account, including, but not limited to, creating a new Motomo Account to circumvent an account suspension or closure.</p>
<p>Violations. Motomo has the right, but not the obligation, to investigate, pursue, and seek to prosecute, litigate, or refer to law enforcement, violations of the Agreement to the fullest extent permissible by the law. Motomo may access, preserve, and disclose any of your information if we are permitted or required to do so by law; if we believe in good faith that it is reasonably necessary to respond to claims asserted against Motomo or to comply with permissible legal process (for example, subpoenas, court orders or warrants); to enforce or administer these Terms; to do so for fraud prevention, risk assessment, investigation, customer support, product development, and debugging purposes; and/or to protect the rights, property, or safety of Motomo, its employees, its users, or members of the public.</p>
<p><br />Motomo reserves the right, at any time and without prior notice, in accordance with applicable law, to remove or disable access to any content that Motomo, at its sole discretion, considers to be objectionable for any reason, in violation of this Agreement, or otherwise harmful to the Services or our community. If we believe you are abusing Motomo, our users, or employees in any way or violating the letter or spirit of any of this Agreement, we may, in our sole discretion and without limiting other remedies, limit, suspend, or terminate your Motomo Account(s) and access to our Services, remove hosted content, deny a claim for coverage, remove and demote your listings, reduce or eliminate any discounts, and take technical and/or legal steps to prevent you from using our Services. Additionally, we reserve the right to refuse or terminate our Services to anyone for any reason at our discretion to the full extent permitted under applicable law.</p>
<p><br />Policy Enforcement. When an issue arises, we may consider the user&rsquo;s performance history and the specific circumstances in applying our Policies. We may choose to be more lenient with policy enforcement in an effort to do the right thing, subject to our sole and absolute discretion.</p>
<p><br />Fees; Collection of Fees. The fees we charge for using our Services and other cost structures can be found on our Policy Pages. When you provide Motomo a payment method, you authorize Motomo, or third-party service providers acting on Motomo&rsquo;s behalf, to store your payment credential for future use in the event you owe Motomo any money. You authorize Motomo to use stored payment credentials for balances, including for Trip Costs, payment, fines and fees (e.g., late fees, security deposits, processing fees and claims costs and related administrative fees). Motomo and its partners will employ all legal methods available to collect the amounts, including the engagements of collection agencies or legal counsel. Motomo, or the collection agencies we retain, may also report information about your Motomo Account to credit bureaus, and as a result, late payments, missed payments, or other defaults on your Motomo Account may be reflected in your credit report. In addition to the amount due, delinquent accounts and/or chargebacks will be charged with fees and/or charges that are incidental to the collection of delinquent accounts and/or chargebacks including, but not limited to, collection fees, convenience fees, and/or other third party charges. You hereby explicitly agree that all communication in relation to delinquent accounts may be made by e-mail or phone, as provided to Motomo by you. Such communication may be made by Motomo or by anyone on its behalf, including but not limited to a third-party collection agent. If you wish to dispute the information Motomo reported to a credit bureau (i.e., Experian, Equifax, or TransUnion) please contact support@motomo.io. If you wish to dispute the information a collection agency reported to a credit bureau regarding your Motomo Account, you must contact the collection agency directly. Any use of referral travel credit is governed by the terms and conditions outlined in this policy.</p>
<p><br />Communications with You. In order to contact you more efficiently, you agree that we may at times contact you using autodialed or prerecorded message calls or text messages at your telephone number(s). We may place such calls or texts primarily to confirm your signup; provide notices regarding your Motomo Account or Motomo Account activity; investigate or prevent fraud; collect a debt owed to us; or communicate urgent messages. We may share your phone number(s) with service providers with whom we contract to assist us in pursuing these interests. We will not share your phone number(s) with third parties for their own purposes without your consent. Standard telephone minute and text and data charges may apply. Where Motomo is required to obtain your consent for such communications, you may choose to revoke your consent.</p>
<p>You authorize Motomo and its partners, without further notice or warning and in our discretion, to monitor or record telephone conversations you or anyone acting on your behalf has with Motomo or its agents for quality control and training purposes. You acknowledge and understand that your communications with Motomo may be overheard, monitored, or recorded without further notice or warning. If you do not wish to have your call recorded, please contact us instead in writing through support@motomo.io.</p>
<p></p>
<p>OTHER LEGAL MATTERS</p>
<p>Motomo Photography. Motomo may offer hosts the option of having photographers take photographs of their vehicles and/or hosts with their vehicles (&ldquo;Images&rdquo;). You alone are responsible for using the Images in connection with your Motomo listing and you warrant that you will cease using the Images if they no longer accurately represent your vehicle. You agree that Motomo is the sole and exclusive owner - or exclusive licensee, as allowed by applicable law - of all right, title, and interest in all copyrights, trademark rights, and any and all other intellectual property rights, including right of publicity rights, worldwide, in the Images regardless of whether you include them in your listing, and you shall take no action to challenge or object to the validity of such rights or Motomo&rsquo;s ownership or registration thereof. You acknowledge that Motomo&rsquo;s may use the Images for advertising, marketing, commercial, and other business purposes in any media or platform, whether in relation to your listing or otherwise, without further notice or compensation. Further, you waive any and all rights to royalties or moral rights you may have in the Images. If you use the Motomo&rsquo;s photography program, you agree that you will not use the Images in connection with sharing your vehicle on any platform, website, or application other than Motomo&rsquo;s. At Motomo&rsquo;s request, you will execute documents and take such further acts as Motomo may reasonably request to assist Motomo to acquire, perfect, and maintain its intellectual property rights and other legal protection in the Images.</p>
<p><br />You understand that if Motomo uses the term &ldquo;Verified Images&rdquo; the term is intended only to indicate a photographic representation of the vehicle at the time the photograph was taken. Verified Images are therefore not an endorsement by Motomo of any user or any vehicle.</p>
<p><br />Motomo Content and User Content License. Subject to your compliance with the provisions of these Terms, Motomo grants you a limited, revocable, non-exclusive, non-transferable license, to access and view any Motomo and/or user content to which you are permitted access, solely for your personal and non-commercial purposes. You have no right to sublicense the license rights granted in this section. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Motomo or its licensors, except for the licenses and rights expressly granted in these Terms.</p>
<p><br />User Content. We may, in our sole discretion, permit you to post, upload, publish, submit or transmit content through our Services such as photographs of you and your vehicle(s), reviews, feedback, and descriptions of you, your vehicle or trip. By making available any content on or through the Services, or through Motomo promotional campaigns, you grant Motomo a worldwide, irrevocable, perpetual (or for the term of the protection), non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, view, copy, adapt, modify, distribute, transfer, publicly display, publicly perform, transmit, stream, broadcast, access, view, and otherwise exploit such content on, through, by means of, or to promote or market the Services. Except as described above with respect to Images, Motomo does not claim any ownership rights in any such content and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit any such content.</p>
<p><br />Promotions. Learn more about our current promotions here. You must be a user in good standing (e.g., not suspended) and comply with these Terms and the promotion rules to qualify for any promotional compensation. Users who attempt to abuse our promotions are subject to cancellation/reversal of the promotion amounts and suspension from the Motomo community. Drivers and Hosts cannot cancel existing reservations to qualify for new promotions. Hosts cannot allow acquaintances, friends, or family to book their vehicle in order to qualify for promotions.</p>
<p><br />Copyright Protection. We respond to notices of alleged copyright infringement and terminate Motomo Accounts of repeat infringers according to the process set out in the US Digital Millennium Copyright Act and similar laws. If you think a user is violating your copyright(s) and want to notify us, you can find information about submitting notices here.</p>
<p><br />Terms for Protection Plans. Motomo is not an insurance company and does not insure hosts or drivers.</p>
<p>Termination. You may discontinue your use of the Services at any time and Motomo may terminate your access to the Services and remove any listings for any reason or no reason to the extent permissible under applicable law. Termination of access to the Services will not release a Party from any obligations You incurred prior to the termination and Motomo may retain and continue to use any information, including but not limited to photography, previously provided by you. Termination of the Agreement will not have any effect on the disclaimers, waiver or liability limitations, or legal disputes provisions under the Agreement and/or any fees due, and all of those terms will survive any termination of the Agreement.</p>
<p><br />No Vehicle Transfer or Assignment. Except as otherwise provided herein, drivers and hosts agree that nothing in these Terms constitutes an actual or purported transfer or assignment of any right or interest in a vehicle or optional Extras shared through the Motomo Services.</p>
<p><br />Disclaimers. MOTOMO PROVIDES SERVICES THAT ENABLE THE BOOKING OF VEHICLES AND OPTIONAL EXTRAS BETWEEN HOSTS AND DRIVERS. EXCEPT AS OTHERWISE PROVIDED IN THESE TERMS, MOTOMO DOES NOT ITSELF PROVIDE RENTAL SERVICES AND/OR INSURANCE SERVICES AND IS NOT RESPONSIBLE FOR ANY OF THE ACTS OR OMISSIONS OF ANY OF THE USERS OF ITS SERVICES, THE MANUFACTURER OF THE VEHICLE OR ANY OPTIONAL EXTRAS, OR ANY THIRD PARTY PROVIDER OF SERVICES (E.G. IN-VEHICLE GPS OR OTHER SYSTEMS). THE SERVICES ARE PROVIDED &ldquo;AS IS&rdquo;, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE EXTENT PERMITTED BY APPLICABLE LAW, WITHOUT LIMITING THE FOREGOING, MOTOMO EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.</p>
<p>Motomo makes no warranty that the Services, including, but not limited to, the listing and/or any vehicle or optional Extra, will meet your requirements or be available on an uninterrupted, secure, or error-free basis. Motomo makes no warranty regarding the quality of any listings, vehicles, hosts, drivers, Extras, the Services, or any content or the accuracy, timeliness, truthfulness, completeness, or reliability of any content obtained through the Services. No advice or information, whether oral or written, obtained from Motomo, its service providers, through the Services or content, will create any warranty not expressly made herein.</p>
<p><br />Limitation of Liability and Waiver. TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOU WAIVE ANY AND ALL RIGHTS YOU HAVE TO SUE OR MAKE CLAIMS AGAINST MOTOMO AND ITS RESPECTIVE SUBSIDIARIES, DIRECTORS, OFFICERS, AGENTS (INCLUDING THIRD PARTY ADMINISTRATORS, INSURANCE PRODUCERS, AND INSURANCE PROVIDERS), OR EMPLOYEES (TOGETHER, THE &ldquo;MOTOMO PARTIES&rdquo;) AND ANY MOTOMO USER (EXCEPT AS DETAILED BELOW FOR TRANSACTIONS WHERE THE HOST PROVIDES THEIR OWN COMMERCIAL/RENTAL PROTECTION PLAN OR WITH RESPECT TO OPTIONAL EXTRAS) FOR ANY DAMAGES OR LOSSES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES INCLUDING, WITHOUT LIMITATION, A VEHICLE NOT BEING AVAILABLE WHEN IT WAS SUPPOSED TO BE, ANY MALFUNCTION OF OR DEFICIENCY IN A VEHICLE, ANY BREACH OF WARRANTY OR OTHER OBLIGATION BY ANY MANUFACTURER OR OTHER THIRD PARTY, ANY PERSONAL INJURY OR PROPERTY DAMAGE SUFFERED BY YOU OR ANY OF YOUR PASSENGERS (EXCEPT IF DAMAGE ARISES FROM AN EXTRA) AND, IN THE CASE OF THE MOTOMO PARTIES, ANY ACTIONS OR INACTION OF THE HOST. NEITHER MOTOMO NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING SERVICES WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA, OR LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE, OR THE COST OF SUBSTITUTE PRODUCTS OR SERVICES, FROM THE USE OF OR INABILITY TO USE THE SERVICES, OR FROM YOUR LISTING OR BOOKING OF ANY VEHICLE OR OPTIONAL EXTRA VIA THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY. Except for our obligations to pay amounts to applicable hosts or drivers pursuant to these Terms, including an approved payment request or claim under a protection plan or applicable insurance policy, in no event will Motomo&rsquo;s or its subsidiaries&rsquo; or insurers&rsquo; aggregate liability arising out of or in connection with this Agreement or your use of the Services, exceed the greater of (i) the amounts you have paid or owe for bookings via the Services as a driver in the twelve month period prior to the event giving rise to the liability, or if you are a host, the amount earned by you in the 12 month period prior to the event giving rise to the liability, or (ii) AUD$100. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN MOTOMO AND YOU. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. ANY SIMILAR LAW, WHICH STATES: &ldquo;A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.&rdquo;</p>
<p>Indemnification. To the extent permitted by applicable law, you agree to release, defend, indemnify, and hold Motomo and its subsidiaries, officers, directors, employees, and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with your access to or use of the Services or your violation of these Terms; your user content; your interaction with any user, booking of a vehicle, or creation of a listing for a vehicle; or the use, condition, or trip, including but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential, or otherwise) of any kind arising in connection with or as a result of a booking, sharing, or use of a vehicle or optional Extra.</p>
<p><br />Liquidated Damages/Contract Penalty. You acknowledge that the actual damages likely to result from you (i) engaging in gray market transactions (i.e., using Motomo to find a driver or vehicle, and then completing a reservation or related transaction partially or wholly independent of Motomo, in order to circumvent the obligation to pay any Motomo Fees) or (ii) registering domains, social media handles, bidding on key words, or otherwise using the Motomo domains, trademarks, or taglines are difficult to estimate and would be difficult for Motomo to prove. You will pay Motomo $5,500 in Liquidated Damages to compensate Motomo for any such conduct. This amount is not intended as a punishment for any such breach.</p>
<p>Motomo is not a rental car company. It does not own a fleet of vehicles, and is not, in the business of renting vehicles to the public. Motomo provides an online platform where car rental businesses businesses and those in need of a vehicle can meet and share vehicles amongst themselves subject to these Terms.</p>
<p><br />Rounding Off. Motomo may, in its sole discretion, round up or down amounts that are payable from or to hosts or drivers to the nearest whole functional base unit in which the currency is denominated (e.g. to the nearest dollar, euro, pound, or other supported currency) where permissible under applicable law.</p>
<p><br />No Agency. Motomo does not appoint you or any other user as its employee, mandatory, legal agent, or form any kind of legal partnership or joint venture. You are not authorized to make any commitments on behalf of Motomo and Motomo will not make commitments on your behalf, except as contemplated by the Services or expressly stated in the Agreement.</p>
<p><br />General. The Agreement states the entire understanding between you and Motomo concerning your access to and use of the Services and supersedes any earlier verbal or written communications between us. With the exception of appointing a custodian to manage your vehicles on your behalf, you may not delegate your legal obligations or transfer any of your rights, in whole or in part, to any third party without advance written consent of Motomo. You will remain responsible for your obligations hereunder in any event. If any provision of the Agreement is construed to be unenforceable, the remaining provisions will not be affected and will continue in full force and effect. A Motomo Director or Officer must agree to any modification or waiver of any term of the Agreement in writing. Motomo&rsquo;s failure to exercise any right under the Agreement will not constitute a waiver of any other right Motomo may have. There is personal vehicle sharing legislation that may apply to you; more information is available in our FAQs.</p>
<p><br />Headings are for reference purposes only and do not limit the scope or extent of such section. Except as otherwise provided in the Agreement, if any provision of these Terms are held to be invalid, void, or for any reason unenforceable, such provision shall be struck out and shall not affect the validity and enforceability of the remaining provisions.</p>
<p><br />Motomo can be contacted at the these addresses. support@motomo.io</p>
<p><br />Translations. Where Motomo has provided you with a translation of the English language version of these Terms or any Policies, in case of any wording discrepancies between the English and any other versions of the Terms and any Policies, the English language wording takes precedence.</p>
<p>&nbsp;</p>
<p>SPECIFIC TERMS FOR DRIVERS</p>
<p>The following Sections also apply if you book a vehicle using the Services:</p>
<p>Fees. You are responsible for paying all fees when they come due. You will be responsible for all of the costs relating to any citations and fines (e.g. tolls, parking tickets, towing fines) incurred during the reservation period. Learn more about the various fees you may incur here.</p>
<p>Your Financial Responsibility Is Primary. With regard to damage, losses, or other liabilities, you acknowledge that, where permissible under applicable law, you are primarily liable for your liabilities under the Agreement, though you may fund that primary liability via any personal insurance you have available to you (e.g., applicable personal auto insurance or insurance from credit cards, etc.) as the primary source of funds. &nbsp;Subject to the coverage and protection available to you, you acknowledge that you are fully responsible for any damage, losses, or other liabilities relating to your activities through the Services. Nothing in these Terms is intended to limit your responsibilities or Motomo&rsquo;s legal rights in connection with your use of the Services. You acknowledge that Motomo may require and hold a deposit as part of the reservation of a vehicle.</p>
<p>In addition to the &rdquo;Terms for Protection Plans&rdquo; section above you understand and agree.</p>
<p>Some hosts offering vehicles for sharing on the Services may not offer commercial liability insurance to you. Motomo is not involved in any facet of the insurance process and is indemnified from any matters relating.</p>
<p><br />Hosts insurance. The Host will bill you directly for any applicable protection plan after booking, not through the Services. In these circumstances, the host may require you to sign additional paperwork, provide a deposit, or pay additional fees, costs, or taxes after booking, for instance when picking up the vehicle. The host may also have additional requirements that differ from Motomo requirements (like requiring a credit card deposit). By booking a vehicle where the Host is providing protection, you agree that the vehicle owner may impose additional terms and fees after booking.</p>
<p>You are fully responsible for paying any damage to the vehicle, subject to the protection plan you selected, as well as deductibles, contribution, fees, expenses, liens, or fines arising out of your use of a vehicle booked through Motomo. If Motomo advances any payment on your behalf, you will continue to be responsible for such amounts and will adhere to Motomo&rsquo;s schedule for repayment of those amounts to Motomo.</p>
<p><br />Use of the Vehicle. When you book a vehicle from a host through Motomo, you must use the vehicle only for your personal use and not for any commercial purposes (e.g. driving other passengers for a fee such as through Uber or Lyft) unless you have express written permission from the host. You may not access a vehicle until the beginning of your reservation period and you must return the vehicle on time and in the correct location. You must present the host with a current, valid driver&rsquo;s license. You must exercise reasonable care in your use of the vehicle. You are required at all times to operate the vehicle safely, and in compliance with all applicable laws, including without limitation, speed limits and prohibitions on impaired or distracted driving. In the event Motomo has any concern about your use of a vehicle, Motomo may terminate your reservation in its discretion at any time and require the return of the vehicle, including recovering the vehicle on behalf of the host. You are required to wear seat belts during the operation of the vehicle and to require that all of your passengers wear seat belts. You are also required to meet any laws or regulations concerning child safety seats and other protections for children. You must not leave the car unlocked or with the keys unsecure (such as in the ignition). The Policies on our Services provide a list of Prohibited Uses of any vehicle shared through the Services. The list isn&rsquo;t meant to be exhaustive. If you have any concerns about your planned use, please contact support@motomo.io. You will be fully financially responsible for any claims, loss, or damage related to your misuse of a vehicle, and your protection plan may be voided. drivers also acknowledge that using a vehicle in a prohibited manner or otherwise breaching the Agreement may lower available liability coverage to legal minimum limits, or nullify coverage, and may furthermore nullify any comprehensive or collision protection and/or protection plan where allowed by applicable law.</p>
<p>Condition of the Vehicle and Optional Extras. You understand that third parties own the vehicles and Extras offered through the Services. Each owner is responsible for complying with all legal requirements (including ensuring the vehicle is registered and insured) and maintaining their vehicle(s) in safe and roadworthy condition. Please complete a visual inspection before you begin your use of the vehicle. If you find damage in your initial inspection, you should upload photos of such pre-existing damage at the start of your reservation here to ensure you are not held responsible for pre-existing damage. If you find damage on your initial inspection and fail to report it, Motomo, third party administrators, or insurance partners, may assume that the damage occurred during your reservation period. If, after your initial inspection, you believe that the vehicle is not safe to drive, please do not use the vehicle; in that event, please contact the Motomo team immediately at support@motomo.io.</p>
<p>Incident Reporting. You will need to use all reasonable efforts to secure evidence from any available witnesses and to provide third-party claims administrators with a written description of the incident and any other information requested, including identity and insurance information of any parties involved in the incident. You are also required to cooperate in any loss investigation conducted by third party claims administrators, or insurers. After an incident, you may not continue to use the vehicle unless you have the explicit permission of the host.</p>
<p>State Laws Regarding Rental Car Theft. It is a crime in most states to fail to return a rental car within a certain period of time after the rental period has expired. The following conduct may result in the reporting of the vehicle you have booked as stolen to law enforcement, possibly subjecting you and any other driver to arrest, and civil and/or criminal penalties, and the voiding of your insurance coverage:</p>
<p><br />If you fail to return the vehicle you booked at the time and place agreed upon with the host and/or designated in your reservation;</p>
<p>If you do not return the vehicle by the end of the reservation period and you have not properly obtained an extension of the reservation through Motomo system as set forth here;</p>
<p>If the vehicle is returned to any place other than the return location on the reservation or agreed upon with the owner. Any damage to, or loss or theft of, a vehicle occurring prior to the host inspecting the vehicle upon return at the end of the reservation is the driver&rsquo;s responsibility;</p>
<p>If you misrepresent facts to the host pertaining to booking, use, or operation of vehicle;</p>
<p>If the vehicle&rsquo;s interior components are stolen or damaged or the vehicle itself is stolen or damaged when the vehicle is left unlocked or running or unattended with the keys not secured during the reservation period;</p>
<p>If you fail or refuse to communicate in &ldquo;good faith&rdquo; with host, police, Motomo, or other authorities with a full report of any accident or vandalism involving the vehicle or otherwise fails to cooperate in the investigation of any accident or vandalism;</p>
<p>If the vehicle is operated by anyone who has given a fictitious name, false address, or a false or invalid driver&rsquo;s license; whose driver&rsquo;s license becomes invalid during the reservation period; who has obtained the keys without permission of the host; or who misrepresents or withholds facts to/from the host or Motomo material to the booking, use or operation of vehicle.</p>
<p>The primary driver who books the reservation is responsible for any private investigation costs Motomo deems necessary to recover a vehicle that is not returned. In addition, a $500 case administration fee will be imposed on the primary driver if Motomo and/or the host has to report a vehicle as stolen to law enforcement due to it not being returned.</p>
<p><br />Repossession. The host may repossess any vehicle booked through the Services without demand, at the driver&rsquo;s expense, if the vehicle is not returned by the end of the reservation, is found illegally parked, apparently abandoned, or used in violation of applicable law or these Terms.</p>
<p><br />Missing Vehicles. If a vehicle you have booked through the Services goes missing and/or is stolen during the reservation period (or extension period), you must immediately return the original ignition key to the host; file a police report immediately after discovering the vehicle is missing or stolen, but in no event more than 24 hours after discovering it has gone missing; and cooperate fully with the host, law enforcement, Motomo, and other authorities in all matters related to the investigation.</p>
<p><br />SPECIFIC TERMS FOR HOSTS</p>
<p>The following Sections also apply if you share your vehicle through the Services:</p>
<p>Information Given at Registration. When you sign up for Motomo, you will identify passenger vehicle(s) that you want to list for sharing through the Services. Each vehicle must meet the requirements found here. You may only use the Services in connection with vehicles that you own or otherwise have all the necessary rights and permissions to share for compensation.</p>
<p><br />Vehicle Availability. Once a trip is booked, you must make the vehicle available or deliver the vehicle as expected by the driver. If you offer the driver the option to pick up your vehicle at a persistent specified location, you must supply the location of the vehicle accurately to Motomo and ensure that the vehicle is available at that location at the beginning of the reservation period. In order to qualify for available protection plans, you must verify that a prospective driver has a current, valid driver&rsquo;s license before you provide the driver your vehicle, and ensure the driver&rsquo;s license matches the name on the reservation and that the person picking up the vehicle appears to match the photograph on a facially valid driver&rsquo;s license.</p>
<p><br />Trip Fees. You will have the ability to set and revise the vehicle&rsquo;s pricing as you choose. Learn more about Automatic Pricing here. Motomo will pay you the amount collected from those who book your vehicle, less the applicable fees payable to Motomo. A current fee schedule can be found here. To the extent you owe Motomo money for any reason, Motomo also reserves the right to deduct those amounts from your payment.</p>
<p><br />Taxes &amp; Airport Permitting Fees. You understand and acknowledge that appropriate governmental agencies, departments, or authorities may take the position that you owe taxes in connection with your use of our Services. Please familiarize yourself with the applicable tax regulations and consult with your personal tax advisor. Further, some airports where you offer delivery may take the position that you must have a permit to use airport premises and remit fees. While Motomo does not believe that rental car permits should apply to peer-to-peer carsharing, not all airport authorities agree with this position.</p>
<p><br />Maintenance. You are required to regularly check your vehicle for any defects in its operations or safety. You promise that, at all times, your vehicle will be in safe and roadworthy condition, in good mechanical condition, and in full compliance with all applicable inspection and registration requirements. You will only list vehicles that are non-salvaged, non-written off, non-washed, and non-branded. You agree to respond to any applicable recall or similar safety notices and to complete any recommended action before allowing your vehicle to be booked. In addition, if Motomo believes that your vehicle does not conform to reasonable standards, Motomo may notify you and reserves the right to remove or decline listing your vehicle until its concerns have been resolved. Motomo may, but does not commit to, undertake efforts to ensure the safety of vehicles booked through the Services. Learn more about our vehicle eligibility requirements here</p>
<p>Physical Damage. There is no insurance or protection made available via the Services.</p>
<p>Other Insurance and Legal Matters. As part of your participation in the Services, you must maintain your own insurance policy and meet any minimum insurance levels required by law. You also promise to maintain registration information and proof of insurance in your vehicle during every reservation period. You agree to provide Motomo with information regarding your policy&rsquo;s coverage as may be requested. You must inform Motomo promptly in the event information previously provided changes.</p>
<p><br />When you choose to provide your own commercial rental, you, as the host, or an authorized representative acting on behalf of the host, shall be exclusively responsible for providing commercial rental insurance coverage for any reservation of your vehicles through Motomo. You shall carry no less than the minimum applicable liability and/or physical damage automobile insurance for your vehicle, your driver, and his/her authorized drivers. You represent and warrant that (1) you are a licensed commercial rental car company or are authorized to act on behalf of and bind a commercial rental car company in connection with listing vehicles on Motomo; or (2) you are an individual or company, or are authorized to act on behalf of, and bind a company, &nbsp;that can offer commercial rental car insurance to drivers.</p>
<p><br />You further acknowledge and agree that you shall receive no protection or coverage from Motomo, or any affiliates, whether that be financial responsibility for physical damage, third-party liability protection, uninsured or underinsured motorist coverage, PIP or any similar coverage or indemnification, roadside assistance, or trust and safety support as part of a booking of your vehicle(s) when you have chosen to provide your own commercial rental insurance. You shall add Motomo as an additional insured on all applicable automobile and excess liability policies. These provisions replace and supersede any representation made by Motomo, or those acting on behalf of Motomo, including but not limited to statements made on the Services, these Terms, FAQs, Policies, emails, and/or marketing materials, concerning insurance and/or protection and roadside assistance.</p>
<p>Motomo reserves the right to, but does not commit to, satisfy itself that you are, or are acting on behalf of, a licensed commercial rental car company and have the ability to offer commercial auto rental insurance to hosts/drivers of your vehicles. If Motomo has any concerns in this regard, you agree that Motomo can automatically, and in its sole discretion, remove your listings, or suspend your Motomo Account.</p>
<p>If you lose the ability to offer commercial rental insurance to your drivers (for example your policy has been canceled or nonrenewed), you must immediately remove your vehicle listing from Motomo. If the change is temporary, you can temporarily remove your vehicle(s) listings. Never let a driver pick up a vehicle or continue to use a vehicle without providing them insurance coverage.</p>
<p>You must disclose on your listing page any applicable additional fees, costs, and/or taxes you assess in addition to other requirements you may impose (such as a security deposit or if you do not accept debit cards, for example). You must never surprise drivers with hidden costs or requirements at pick-up. Motomo reserves the right, in its sole discretion, to default your vehicles back to a Standard protection plan, remove your listings, or suspend your Motomo Account for failure to be transparent up front with drivers about fees, costs, and requirements in your vehicle listing page.</p>
<p>You acknowledge that the actual damages likely to result from breach of this Section are difficult to estimate and would be difficult for Motomo to prove. You will pay Motomo AUD$5,500 in Liquidated Damages/Contract Penalties to compensate Motomo for any such conduct. This amount is not intended as a punishment for any such breach.</p>
<p>You shall defend, indemnify, and hold Motomo, its subsidiaries, affiliates, employees, officers, directors, and agents, and any of your drivers or their authorized drivers, harmless from and against any and all claims, demands, suits, judgments, costs, expenses, liabilities, attorneys fees, damages, consequential damages, punitive damages, property damage, personal injury, theft or otherwise, without limitation, related to or arising out of any reservation or use of any vehicles, including without limitation, any vehicle damage, personal injury or property damage.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
    </div>
  );
};

TermsOfService.defaultProps = {
  rootClassName: null,
  className: null,
};

const { string } = PropTypes;

TermsOfService.propTypes = {
  rootClassName: string,
  className: string,
};

export default TermsOfService;
